AWSTemplateFormatVersion: '2010-09-09'
Description: Creates a KMS key and grants access to other accounts
Parameters:
  devAccount:
    Description: AWS account number for DEV
    Type: String
  prodAccount:
    Description: AWS account number for PROD
    Type: String
  projectName:
    Description: Name of the Project
    Type: String
    Default: sample-lambda
Resources:
  KmsKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Used by target account roles to access artifacts in the artifact bucket
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Ref AWS::StackName
        Statement:
          -
            Sid: Key administration
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
            Resource: "*"
          -
            Sid: Pipeline and target account access
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${prodAccount}:root
                - !Sub arn:aws:iam::${devAccount}:root
                - !Sub arn:aws:iam::${AWS::AccountId}:role/${projectName}-CodeBuildRole
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/codepipeline-crossaccounts
      TargetKeyId: !Ref KmsKey
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain

Outputs:
  S3KmsKey:
    Value: !GetAtt KmsKey.Arn
  ArtifactBucket:
    Value: !Ref ArtifactBucket

